import json
from datetime import datetime
from urllib.error import URLError
from urllib.request import Request, urlopen

from app.models import GoalPlan, MemoryEntity, PlanTask, PlanTaskSession, db
from app.services.memory_engine import remember, upsert_entity


VALID_CADENCES = {"daily", "weekly", "monthly"}
VALID_STATUSES = {"not_started", "in_progress", "completed"}

ROADMAPS = {
    "operating systems": [
        ["Processes", "Threads"],
        ["CPU Scheduling", "Deadlocks"],
        ["Memory Management", "Virtual Memory"],
        ["File Systems", "I/O Systems"],
    ],
    "python": [
        ["Syntax and data structures", "Functions and modules"],
        ["Object-oriented Python", "Testing and debugging"],
        ["APIs and data handling", "Automation project"],
        ["Performance basics", "Capstone review"],
    ],
    "machine learning": [
        ["Math and data preparation", "Regression"],
        ["Classification", "Model evaluation"],
        ["Feature engineering", "Tree-based models"],
        ["Neural network basics", "End-to-end project"],
    ],
}


def create_goal_plan(data, config):
    goal_text = str(data.get("goal") or data.get("title") or "").strip()
    if not goal_text:
        raise ValueError("goal is required")
    cadence = str(data.get("cadence") or "weekly").strip().lower()
    if cadence not in VALID_CADENCES:
        raise ValueError("cadence must be daily, weekly, or monthly")
    duration = max(1, min(24, int(data.get("duration_units") or 4)))

    goal = upsert_entity(
        {
            "entity_type": "goal",
            "name": goal_text,
            "status": "in_progress",
            "summary": f"{cadence.title()} adaptive roadmap generated by AiOS.",
        }
    )
    periods, generated_by = generate_roadmap(goal_text, cadence, duration, config)
    plan = GoalPlan(
        goal=goal,
        title=goal_text[:180],
        cadence=cadence,
        duration_units=len(periods),
        strategy="Complete tasks in order. AiOS promotes the next task as progress is recorded.",
        generated_by=generated_by,
    )
    db.session.add(plan)
    db.session.flush()

    position = 1
    for period_number, topics in enumerate(periods, start=1):
        for topic in topics:
            db.session.add(
                PlanTask(
                    plan=plan,
                    title=str(topic.get("title") or topic)[:180],
                    description=str(topic.get("description") or "") if isinstance(topic, dict) else "",
                    period_number=period_number,
                    position=position,
                    estimated_minutes=max(15, int(topic.get("estimated_minutes") or 90))
                    if isinstance(topic, dict)
                    else 90,
                    resources_json=json.dumps(topic.get("resources") or [], ensure_ascii=True)
                    if isinstance(topic, dict)
                    else "[]",
                )
            )
            position += 1
    db.session.flush()
    adapt_plan(plan)
    return plan


def generate_roadmap(goal, cadence, duration, config):
    if config.get("AI_PROVIDER") == "ollama":
        generated = generate_with_ollama(goal, cadence, duration, config)
        if generated:
            return generated, f"ollama:{config.get('OLLAMA_MODEL', '')}"
    return fallback_roadmap(goal, duration), "rule_based"


def generate_with_ollama(goal, cadence, duration, config):
    prompt = (
        "Create a concise learning or project roadmap. Return only JSON as "
        '{"periods":[[{"title":"","description":"","estimated_minutes":90,"resources":[]}]]}. '
        f"Goal: {goal}. Cadence: {cadence}. Periods: {duration}. "
        "Use 1 to 3 actionable tasks per period."
    )
    payload = {
        "model": config.get("OLLAMA_MODEL") or "qwen2.5:3b",
        "prompt": prompt,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0.2},
    }
    try:
        request = Request(
            f"{str(config.get('OLLAMA_URL') or 'http://localhost:11434').rstrip('/')}/api/generate",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urlopen(request, timeout=45) as response:
            result = json.loads(response.read().decode("utf-8"))
        periods = json.loads(result.get("response", "{}")).get("periods")
        if isinstance(periods, list) and periods:
            return periods[:duration]
    except (OSError, URLError, ValueError, json.JSONDecodeError):
        return None
    return None


def fallback_roadmap(goal, duration):
    lowered = goal.lower()
    template = next((topics for key, topics in ROADMAPS.items() if key in lowered), None)
    if template is None:
        subject = goal.removeprefix("I want to ").removeprefix("Learn ").strip().rstrip(".")
        template = [
            [f"{subject} fundamentals", "Core terminology"],
            ["Guided practice", "Build a small exercise"],
            ["Intermediate concepts", "Apply concepts to a project"],
            ["Review and capstone", "Document what you learned"],
        ]
    periods = []
    for index in range(duration):
        topics = template[min(index, len(template) - 1)]
        periods.append([{"title": topic, "estimated_minutes": 90, "resources": []} for topic in topics])
    return periods


def update_task(task_id, data, config):
    task = db.session.get(PlanTask, int(task_id))
    if task is None:
        raise ValueError("task not found")
    status = str(data.get("status") or task.status).strip().lower()
    if status not in VALID_STATUSES:
        raise ValueError("invalid task status")
    now = datetime.utcnow()
    if status == "in_progress" and not task.started_at:
        task.started_at = now
    if status == "completed":
        task.started_at = task.started_at or now
        task.completed_at = task.completed_at or now
    task.status = status
    if "resources" in data:
        task.resources_json = json.dumps(parse_resources(data.get("resources")), ensure_ascii=True)
    if data.get("summary"):
        task.ai_summary = str(data.get("summary")).strip()
    adapt_plan(task.plan)
    if status == "completed":
        remember(
            {
                "entity_id": task.plan.goal_id,
                "fact_type": "learning_summary",
                "content": f"Completed {task.title}. {task.ai_summary or ''}".strip(),
                "source": "goal_planner",
                "importance": 0.8,
            },
            config,
        )
    return task


def log_task_session(task_id, data, config):
    task = db.session.get(PlanTask, int(task_id))
    if task is None:
        raise ValueError("task not found")
    started_at = parse_time(data.get("started_at")) or datetime.utcnow()
    ended_at = parse_time(data.get("ended_at"))
    duration = int(data.get("duration_minutes") or 0)
    if ended_at and duration <= 0:
        duration = max(0, round((ended_at - started_at).total_seconds() / 60))
    session = PlanTaskSession(
        task=task,
        started_at=started_at,
        ended_at=ended_at,
        duration_minutes=duration,
        resources_json=json.dumps(parse_resources(data.get("resources")), ensure_ascii=True),
        summary=str(data.get("summary") or "").strip(),
    )
    db.session.add(session)
    task.started_at = task.started_at or started_at
    task.status = "completed" if data.get("completed") else "in_progress"
    if data.get("completed"):
        task.completed_at = ended_at or datetime.utcnow()
        task.ai_summary = session.summary or summarize_task(task)
    adapt_plan(task.plan)
    return session


def adapt_plan(plan):
    ordered = sorted(plan.tasks, key=lambda item: item.position)
    incomplete = [task for task in ordered if task.status != "completed"]
    for task in ordered:
        task.suggested_next = None
    for index, task in enumerate(ordered):
        following = next((item for item in ordered[index + 1 :] if item.status != "completed"), None)
        if task.status == "completed" and following:
            task.suggested_next = following.title
    if not incomplete:
        plan.status = "completed"
        plan.goal.status = "completed"
    else:
        plan.status = "active"
        plan.goal.status = "in_progress"


def planner_overview():
    plans = GoalPlan.query.order_by(GoalPlan.updated_at.desc()).all()
    return {
        "plans": [serialize_plan(plan, include_tasks=True) for plan in plans],
        "counts": {
            "plans": len(plans),
            "completed_tasks": PlanTask.query.filter_by(status="completed").count(),
            "active_tasks": PlanTask.query.filter_by(status="in_progress").count(),
            "minutes": sum(session.duration_minutes for session in PlanTaskSession.query.all()),
        },
    }


def serialize_plan(plan, include_tasks=False):
    tasks = sorted(plan.tasks, key=lambda item: item.position)
    completed = sum(task.status == "completed" for task in tasks)
    result = {
        "id": plan.id,
        "goal_id": plan.goal_id,
        "title": plan.title,
        "cadence": plan.cadence,
        "status": plan.status,
        "duration_units": plan.duration_units,
        "generated_by": plan.generated_by,
        "completed_tasks": completed,
        "total_tasks": len(tasks),
        "progress_percent": round(completed / len(tasks) * 100) if tasks else 0,
    }
    if include_tasks:
        result["tasks"] = [serialize_task(task) for task in tasks]
    return result


def serialize_task(task):
    return {
        "id": task.id,
        "title": task.title,
        "description": task.description,
        "period_number": task.period_number,
        "position": task.position,
        "status": task.status,
        "estimated_minutes": task.estimated_minutes,
        "time_spent_minutes": sum(session.duration_minutes for session in task.sessions),
        "started_at": task.started_at.isoformat() if task.started_at else None,
        "completed_at": task.completed_at.isoformat() if task.completed_at else None,
        "resources": parse_resources(task.resources_json),
        "summary": task.ai_summary,
        "suggested_next": task.suggested_next,
    }


def summarize_task(task):
    summaries = [session.summary for session in task.sessions if session.summary]
    return " ".join(summaries) or f"Completed {task.title}."


def parse_resources(value):
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if not value:
        return []
    try:
        parsed = json.loads(value)
        if isinstance(parsed, list):
            return [str(item).strip() for item in parsed if str(item).strip()]
    except (TypeError, json.JSONDecodeError):
        pass
    return [item.strip() for item in str(value).replace("\n", ",").split(",") if item.strip()]


def parse_time(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).replace(tzinfo=None)
    except ValueError:
        return None
